=begin
#Open Banking

#OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

The version of the OpenAPI document: 1.19.0
Contact: apisupport@mastercard.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module OpenBanking
  class CashFlowCashFlowCharacteristic
    # List of attributes for each month
    attr_accessor :monthly_cash_flow_characteristics

    # Average (Total Credits - Total Debits) for the account
    attr_accessor :average_monthly_net

    # Average (Total Credits - Total Debits) without transfers for the account
    attr_accessor :average_monthly_net_less_transfers

    # Sum of all monthly (Total Credits - Total Debits) each month for the account
    attr_accessor :twelve_month_total_net

    # Sum of all monthly (Total Credits - Total Debits) without transfers for the account
    attr_accessor :twelve_month_total_net_less_transfers

    # 6 Month Average (Total Credits - Total Debits)
    attr_accessor :six_month_average_total_credits_less_total_debits

    # 6 Month Average (Total Credits - Total Debits) - (Without Transfers)
    attr_accessor :six_month_average_total_credits_less_total_debits_less_transfers

    # 2 Month Average (Total Credits - Total Debits)
    attr_accessor :two_month_average_total_credits_less_total_debits

    # 2 Month Average (Total Credits - Total Debits) - (Without Transfers)
    attr_accessor :two_month_average_total_credits_less_total_debits_less_transfers

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'monthly_cash_flow_characteristics' => :'monthlyCashFlowCharacteristics',
        :'average_monthly_net' => :'averageMonthlyNet',
        :'average_monthly_net_less_transfers' => :'averageMonthlyNetLessTransfers',
        :'twelve_month_total_net' => :'twelveMonthTotalNet',
        :'twelve_month_total_net_less_transfers' => :'twelveMonthTotalNetLessTransfers',
        :'six_month_average_total_credits_less_total_debits' => :'sixMonthAverageTotalCreditsLessTotalDebits',
        :'six_month_average_total_credits_less_total_debits_less_transfers' => :'sixMonthAverageTotalCreditsLessTotalDebitsLessTransfers',
        :'two_month_average_total_credits_less_total_debits' => :'twoMonthAverageTotalCreditsLessTotalDebits',
        :'two_month_average_total_credits_less_total_debits_less_transfers' => :'twoMonthAverageTotalCreditsLessTotalDebitsLessTransfers'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'monthly_cash_flow_characteristics' => :'Array<CashFlowMonthlyCashFlowCharacteristics>',
        :'average_monthly_net' => :'Float',
        :'average_monthly_net_less_transfers' => :'Float',
        :'twelve_month_total_net' => :'Float',
        :'twelve_month_total_net_less_transfers' => :'Float',
        :'six_month_average_total_credits_less_total_debits' => :'Float',
        :'six_month_average_total_credits_less_total_debits_less_transfers' => :'Float',
        :'two_month_average_total_credits_less_total_debits' => :'Float',
        :'two_month_average_total_credits_less_total_debits_less_transfers' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenBanking::CashFlowCashFlowCharacteristic` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenBanking::CashFlowCashFlowCharacteristic`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'monthly_cash_flow_characteristics')
        if (value = attributes[:'monthly_cash_flow_characteristics']).is_a?(Array)
          self.monthly_cash_flow_characteristics = value
        end
      else
        self.monthly_cash_flow_characteristics = nil
      end

      if attributes.key?(:'average_monthly_net')
        self.average_monthly_net = attributes[:'average_monthly_net']
      else
        self.average_monthly_net = nil
      end

      if attributes.key?(:'average_monthly_net_less_transfers')
        self.average_monthly_net_less_transfers = attributes[:'average_monthly_net_less_transfers']
      else
        self.average_monthly_net_less_transfers = nil
      end

      if attributes.key?(:'twelve_month_total_net')
        self.twelve_month_total_net = attributes[:'twelve_month_total_net']
      end

      if attributes.key?(:'twelve_month_total_net_less_transfers')
        self.twelve_month_total_net_less_transfers = attributes[:'twelve_month_total_net_less_transfers']
      end

      if attributes.key?(:'six_month_average_total_credits_less_total_debits')
        self.six_month_average_total_credits_less_total_debits = attributes[:'six_month_average_total_credits_less_total_debits']
      end

      if attributes.key?(:'six_month_average_total_credits_less_total_debits_less_transfers')
        self.six_month_average_total_credits_less_total_debits_less_transfers = attributes[:'six_month_average_total_credits_less_total_debits_less_transfers']
      end

      if attributes.key?(:'two_month_average_total_credits_less_total_debits')
        self.two_month_average_total_credits_less_total_debits = attributes[:'two_month_average_total_credits_less_total_debits']
      end

      if attributes.key?(:'two_month_average_total_credits_less_total_debits_less_transfers')
        self.two_month_average_total_credits_less_total_debits_less_transfers = attributes[:'two_month_average_total_credits_less_total_debits_less_transfers']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @monthly_cash_flow_characteristics.nil?
        invalid_properties.push('invalid value for "monthly_cash_flow_characteristics", monthly_cash_flow_characteristics cannot be nil.')
      end

      if @average_monthly_net.nil?
        invalid_properties.push('invalid value for "average_monthly_net", average_monthly_net cannot be nil.')
      end

      if @average_monthly_net_less_transfers.nil?
        invalid_properties.push('invalid value for "average_monthly_net_less_transfers", average_monthly_net_less_transfers cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @monthly_cash_flow_characteristics.nil?
      return false if @average_monthly_net.nil?
      return false if @average_monthly_net_less_transfers.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          monthly_cash_flow_characteristics == o.monthly_cash_flow_characteristics &&
          average_monthly_net == o.average_monthly_net &&
          average_monthly_net_less_transfers == o.average_monthly_net_less_transfers &&
          twelve_month_total_net == o.twelve_month_total_net &&
          twelve_month_total_net_less_transfers == o.twelve_month_total_net_less_transfers &&
          six_month_average_total_credits_less_total_debits == o.six_month_average_total_credits_less_total_debits &&
          six_month_average_total_credits_less_total_debits_less_transfers == o.six_month_average_total_credits_less_total_debits_less_transfers &&
          two_month_average_total_credits_less_total_debits == o.two_month_average_total_credits_less_total_debits &&
          two_month_average_total_credits_less_total_debits_less_transfers == o.two_month_average_total_credits_less_total_debits_less_transfers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [monthly_cash_flow_characteristics, average_monthly_net, average_monthly_net_less_transfers, twelve_month_total_net, twelve_month_total_net_less_transfers, six_month_average_total_credits_less_total_debits, six_month_average_total_credits_less_total_debits_less_transfers, two_month_average_total_credits_less_total_debits, two_month_average_total_credits_less_total_debits_less_transfers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenBanking.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
