=begin
#Open Banking

#OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

The version of the OpenAPI document: 1.19.0
Contact: apisupport@mastercard.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module OpenBanking
  class VOIEPaystubWithStatementPayStatement
    # The pay period of the pay statement
    attr_accessor :pay_period

    # This will display true if the pay statement is billable. If a pay statement has been digitized previously, this will display as false as it will not be billable.
    attr_accessor :billable

    # The asset ID of the stored pay statement
    attr_accessor :asset_id

    # The listed pay date for the pay statement
    attr_accessor :pay_date

    # The beginning of the pay period
    attr_accessor :start_date

    # The end of the pay period
    attr_accessor :end_date

    # The total pay after deductions for the employee for the current pay period
    attr_accessor :net_pay_current

    # The total accumulation of pay after deductions for the employee for the current pay year
    attr_accessor :net_pay_ytd

    # The total pay before deductions for the employee for the current pay period
    attr_accessor :gross_pay_current

    # The total accumulation of pay before deductions for the employee for the current pay year
    attr_accessor :gross_pay_ytd

    # The payroll provider extracted from the pay statement
    attr_accessor :payroll_provider

    attr_accessor :employer

    attr_accessor :employee

    # Information pertaining to the earnings on the pay statement
    attr_accessor :pay_stat

    # Information pertaining to the direct deposits on the pay statement
    attr_accessor :direct_deposits

    # Not populated for the voieWithStatement style of paystub report. For the VOIE - Paystub (with TXVerify) reports this would include details of the financial institution accounts and income streams with matching transactions to the pay statement.
    attr_accessor :institutions

    # Error code for the asset
    attr_accessor :error_code

    # Error message for the asset
    attr_accessor :error_message

    attr_accessor :monthly_income

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pay_period' => :'payPeriod',
        :'billable' => :'billable',
        :'asset_id' => :'assetId',
        :'pay_date' => :'payDate',
        :'start_date' => :'startDate',
        :'end_date' => :'endDate',
        :'net_pay_current' => :'netPayCurrent',
        :'net_pay_ytd' => :'netPayYTD',
        :'gross_pay_current' => :'grossPayCurrent',
        :'gross_pay_ytd' => :'grossPayYTD',
        :'payroll_provider' => :'payrollProvider',
        :'employer' => :'employer',
        :'employee' => :'employee',
        :'pay_stat' => :'payStat',
        :'direct_deposits' => :'directDeposits',
        :'institutions' => :'institutions',
        :'error_code' => :'errorCode',
        :'error_message' => :'errorMessage',
        :'monthly_income' => :'monthlyIncome'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pay_period' => :'String',
        :'billable' => :'Boolean',
        :'asset_id' => :'String',
        :'pay_date' => :'Integer',
        :'start_date' => :'Integer',
        :'end_date' => :'Integer',
        :'net_pay_current' => :'Float',
        :'net_pay_ytd' => :'Float',
        :'gross_pay_current' => :'Float',
        :'gross_pay_ytd' => :'Float',
        :'payroll_provider' => :'String',
        :'employer' => :'Employer',
        :'employee' => :'Employee',
        :'pay_stat' => :'Array<PayStat>',
        :'direct_deposits' => :'Array<DirectDeposit>',
        :'institutions' => :'Array<String>',
        :'error_code' => :'Integer',
        :'error_message' => :'String',
        :'monthly_income' => :'PaystubTxVerifyMonthlyIncomeRecord'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'PayStatementForVoie'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenBanking::VOIEPaystubWithStatementPayStatement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenBanking::VOIEPaystubWithStatementPayStatement`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pay_period')
        self.pay_period = attributes[:'pay_period']
      end

      if attributes.key?(:'billable')
        self.billable = attributes[:'billable']
      else
        self.billable = nil
      end

      if attributes.key?(:'asset_id')
        self.asset_id = attributes[:'asset_id']
      else
        self.asset_id = nil
      end

      if attributes.key?(:'pay_date')
        self.pay_date = attributes[:'pay_date']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      end

      if attributes.key?(:'net_pay_current')
        self.net_pay_current = attributes[:'net_pay_current']
      end

      if attributes.key?(:'net_pay_ytd')
        self.net_pay_ytd = attributes[:'net_pay_ytd']
      end

      if attributes.key?(:'gross_pay_current')
        self.gross_pay_current = attributes[:'gross_pay_current']
      end

      if attributes.key?(:'gross_pay_ytd')
        self.gross_pay_ytd = attributes[:'gross_pay_ytd']
      end

      if attributes.key?(:'payroll_provider')
        self.payroll_provider = attributes[:'payroll_provider']
      end

      if attributes.key?(:'employer')
        self.employer = attributes[:'employer']
      else
        self.employer = nil
      end

      if attributes.key?(:'employee')
        self.employee = attributes[:'employee']
      else
        self.employee = nil
      end

      if attributes.key?(:'pay_stat')
        if (value = attributes[:'pay_stat']).is_a?(Array)
          self.pay_stat = value
        end
      else
        self.pay_stat = nil
      end

      if attributes.key?(:'direct_deposits')
        if (value = attributes[:'direct_deposits']).is_a?(Array)
          self.direct_deposits = value
        end
      end

      if attributes.key?(:'institutions')
        if (value = attributes[:'institutions']).is_a?(Array)
          self.institutions = value
        end
      else
        self.institutions = nil
      end

      if attributes.key?(:'error_code')
        self.error_code = attributes[:'error_code']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'monthly_income')
        self.monthly_income = attributes[:'monthly_income']
      else
        self.monthly_income = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @billable.nil?
        invalid_properties.push('invalid value for "billable", billable cannot be nil.')
      end

      if @asset_id.nil?
        invalid_properties.push('invalid value for "asset_id", asset_id cannot be nil.')
      end

      if @employer.nil?
        invalid_properties.push('invalid value for "employer", employer cannot be nil.')
      end

      if @employee.nil?
        invalid_properties.push('invalid value for "employee", employee cannot be nil.')
      end

      if @pay_stat.nil?
        invalid_properties.push('invalid value for "pay_stat", pay_stat cannot be nil.')
      end

      if @institutions.nil?
        invalid_properties.push('invalid value for "institutions", institutions cannot be nil.')
      end

      if @monthly_income.nil?
        invalid_properties.push('invalid value for "monthly_income", monthly_income cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @billable.nil?
      return false if @asset_id.nil?
      return false if @employer.nil?
      return false if @employee.nil?
      return false if @pay_stat.nil?
      return false if @institutions.nil?
      return false if @monthly_income.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pay_period == o.pay_period &&
          billable == o.billable &&
          asset_id == o.asset_id &&
          pay_date == o.pay_date &&
          start_date == o.start_date &&
          end_date == o.end_date &&
          net_pay_current == o.net_pay_current &&
          net_pay_ytd == o.net_pay_ytd &&
          gross_pay_current == o.gross_pay_current &&
          gross_pay_ytd == o.gross_pay_ytd &&
          payroll_provider == o.payroll_provider &&
          employer == o.employer &&
          employee == o.employee &&
          pay_stat == o.pay_stat &&
          direct_deposits == o.direct_deposits &&
          institutions == o.institutions &&
          error_code == o.error_code &&
          error_message == o.error_message &&
          monthly_income == o.monthly_income
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pay_period, billable, asset_id, pay_date, start_date, end_date, net_pay_current, net_pay_ytd, gross_pay_current, gross_pay_ytd, payroll_provider, employer, employee, pay_stat, direct_deposits, institutions, error_code, error_message, monthly_income].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenBanking.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
