=begin
#Open Banking

#OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

The version of the OpenAPI document: 1.19.0
Contact: apisupport@mastercard.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenBanking::BusinessesAPIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessesAPIApi' do
  before do
    # run before each test
    @api_instance = OpenBanking::BusinessesAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessesAPIApi' do
    it 'should create an instance of BusinessesAPIApi' do
      expect(@api_instance).to be_instance_of(OpenBanking::BusinessesAPIApi)
    end
  end

  # unit tests for add_business_details
  # Create a New Business for a Customer
  # Create a new business record for the associated customer. A customer can have one business record associated.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
  # @param customer_id Unique identifier of the customer
  # @param new_business 
  # @param [Hash] opts the optional parameters
  # @return [Business]
  describe 'add_business_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_by_customer
  # Get Business for Customer
  # Retrieve business details associated with a specific customer. By providing the unique customer identifier, details about the associated business can be accessed.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
  # @param customer_id Unique identifier of the customer
  # @param [Hash] opts the optional parameters
  # @return [Array<Business>]
  describe 'get_business_by_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_by_id
  # Get Business by ID
  # Retrieve business details.  _Supported regions_: ![\\U0001F1FA\\U0001F1F8](https://flagcdn.com/20x15/us.png)
  # @param business_id Unique identifier of the business
  # @param [Hash] opts the optional parameters
  # @return [Array<Business>]
  describe 'get_business_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_business
  # Update Business by ID
  # Update the details of a business based on its unique identifier. By providing the specific business ID and the updated information in the request, modifications can be made to the business&#39;s profile.  _Supported regions_: ![🇺🇸](https://flagcdn.com/20x15/us.png)
  # @param business_id Unique identifier of the business
  # @param new_business 
  # @param [Hash] opts the optional parameters
  # @return [Business]
  describe 'update_business test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
