=begin
#Open Banking

#OpenAPI specification for Finicity APIs.  Open Banking solutions in the US are provided by Finicity, a Mastercard company.

The version of the OpenAPI document: 1.19.0
Contact: apisupport@mastercard.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenBanking::BalanceAnalyticsBusinessSummary
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenBanking::BalanceAnalyticsBusinessSummary do
  let(:instance) { OpenBanking::BalanceAnalyticsBusinessSummary.new }

  describe 'test an instance of BalanceAnalyticsBusinessSummary' do
    it 'should create an instance of BalanceAnalyticsBusinessSummary' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenBanking::BalanceAnalyticsBusinessSummary)
    end
  end

  describe 'test attribute "balance_analytics_metrics"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "current_report_request"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "historic_data_availability"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
